# Uncomment the next line to define a global platform for your project
 platform :ios, '8.0'

target 'LocNaviWebSDK_Demo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LocNaviWebSDK_Demo
  #本地路径
#  pod 'LocNaviWebSDK'
  #本地路径
  pod 'LocNaviWebSDK', :path => '../'
  pod 'XJLocation', :path => '../'
  
  target 'LocNaviWebSDK_DemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LocNaviWebSDK_DemoUITests' do
    # Pods for testing
  end

end
